stages:
    - build jar
    - build docker
#    - public docker


build app:
    before_script:
        - mvn -v
    script:
        - mvn clean package -DskipTests -e
    artifacts:
        paths:
            - target/*.jar
        expire_in: 1 day
    stage: build jar
    only:
        - merge_request

build docker:
    script:
        - docker build -t docker.trainee.ru.com/group10-back .
    stage: build docker
    only: 
        - merge_request